// Database-derived types.
//
// Owner: Database agent.
//
// This file is the hand-authored mirror of the Supabase schema defined
// under `supabase/migrations/`. Once a Supabase project is provisioned
// (Phase 1), this file will be regenerated by `supabase gen types
// typescript` and the hand-authored Row/Insert/Update shapes below
// replaced. Until then, this file IS the contract.
//
// Conventions:
//   - Every table appears as `Tables['<name>']` with Row/Insert/Update.
//   - Enums appear as string-literal unions in `Enums` and are also
//     re-exported from `./enums.ts` for direct import.
//   - geography(Point, 4326) values are serialized as GeoJSON Point
//     objects when read via PostgREST.

import type {
  BookingStatus,
  BudgetTier,
  CancellationParty,
  EscrowStatus,
  MealType,
  MessageType,
  PaymentStatus,
  RequestStatus,
  ReviewSubjectType,
  VerificationStatus,
} from './enums';

/** GeoJSON Point as returned by PostgREST for geography(Point, 4326). */
export interface GeoJSONPoint {
  type: 'Point';
  /** [longitude, latitude] */
  coordinates: [number, number];
}

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

/**
 * Insert shape: columns in `Required` are required, everything else is
 * optional (because the database provides a default or accepts NULL).
 */
type Insert<R, Required extends keyof R> = Pick<R, Required> &
  Partial<Omit<R, Required>>;

// ---------------------------------------------------------------------------
// Row shapes
// ---------------------------------------------------------------------------

export interface UserRow {
  id: string;
  email: string;
  display_name: string;
  bio: string | null;
  avatar_path: string | null;
  is_seeker: boolean;
  is_companion: boolean;
  seeker_verification_status: VerificationStatus;
  languages: string[];
  interests: string[];
  dietary_preferences: string[];
  guidelines_accepted_at: string | null;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface CompanionProfileRow {
  user_id: string;
  headline: string | null;
  bio_long: string | null;
  rate_cents: number;
  rate_currency: string;
  meal_types: MealType[];
  service_area_center: GeoJSONPoint;
  service_radius_m: number;
  verification_status: VerificationStatus;
  verified_at: string | null;
  stripe_connect_account_id: string | null;
  stripe_payouts_enabled: boolean;
  avg_rating: number | null;
  rating_count: number;
  created_at: string;
  updated_at: string;
}

export interface AvailabilityRow {
  id: string;
  companion_user_id: string;
  day_of_week: number;
  start_time: string;
  end_time: string;
  meal_type: MealType;
  timezone: string;
  created_at: string;
  updated_at: string;
}

export interface MealRequestRow {
  id: string;
  seeker_user_id: string;
  companion_user_id: string;
  meal_type: MealType;
  proposed_time: string;
  proposed_location_text: string | null;
  proposed_location: GeoJSONPoint | null;
  seeker_message: string | null;
  status: RequestStatus;
  decline_reason: string | null;
  responded_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface BookingRow {
  id: string;
  request_id: string;
  seeker_user_id: string;
  companion_user_id: string;
  meal_type: MealType;
  scheduled_for: string;
  restaurant_name: string | null;
  restaurant_place_id: string | null;
  restaurant_address: string | null;
  restaurant_location: GeoJSONPoint | null;
  budget_tier: BudgetTier | null;
  budget_amount_cents: number | null;
  companionship_fee_cents: number;
  fee_currency: string;
  status: BookingStatus;
  seeker_confirmed_at: string | null;
  companion_confirmed_at: string | null;
  completed_at: string | null;
  cancelled_at: string | null;
  cancelled_by: CancellationParty | null;
  cancellation_reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface PaymentRow {
  id: string;
  booking_id: string;
  amount_cents: number;
  platform_fee_cents: number;
  currency: string;
  stripe_payment_intent_id: string | null;
  stripe_charge_id: string | null;
  stripe_transfer_id: string | null;
  stripe_refund_id: string | null;
  payment_status: PaymentStatus;
  escrow_status: EscrowStatus;
  captured_at: string | null;
  released_at: string | null;
  refunded_at: string | null;
  failure_reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface MessageRow {
  id: string;
  booking_id: string;
  sender_user_id: string | null;
  message_type: MessageType;
  body: string;
  created_at: string;
}

export interface ReviewRow {
  id: string;
  booking_id: string;
  author_user_id: string;
  subject_user_id: string;
  subject_type: ReviewSubjectType;
  rating: number;
  body: string | null;
  created_at: string;
  updated_at: string;
}

// ---------------------------------------------------------------------------
// Insert / Update shapes
// ---------------------------------------------------------------------------
// Insert: only NOT NULL columns without a database default are required.
// Update: everything optional. Caller specifies what to change.

export type UserInsert = Insert<UserRow, 'id' | 'email' | 'display_name'>;
export type UserUpdate = Partial<UserRow>;

export type CompanionProfileInsert = Insert<
  CompanionProfileRow,
  'user_id' | 'rate_cents' | 'service_area_center' | 'service_radius_m'
>;
export type CompanionProfileUpdate = Partial<CompanionProfileRow>;

export type AvailabilityInsert = Insert<
  AvailabilityRow,
  'companion_user_id' | 'day_of_week' | 'start_time' | 'end_time' | 'meal_type' | 'timezone'
>;
export type AvailabilityUpdate = Partial<AvailabilityRow>;

export type MealRequestInsert = Insert<
  MealRequestRow,
  'seeker_user_id' | 'companion_user_id' | 'meal_type' | 'proposed_time'
>;
export type MealRequestUpdate = Partial<MealRequestRow>;

export type BookingInsert = Insert<
  BookingRow,
  | 'request_id'
  | 'seeker_user_id'
  | 'companion_user_id'
  | 'meal_type'
  | 'scheduled_for'
  | 'companionship_fee_cents'
>;
export type BookingUpdate = Partial<BookingRow>;

export type PaymentInsert = Insert<PaymentRow, 'booking_id' | 'amount_cents'>;
export type PaymentUpdate = Partial<PaymentRow>;

export type MessageInsert = Insert<MessageRow, 'booking_id' | 'body'>;
/** Messages are immutable; no UPDATE policy exists. */
export type MessageUpdate = never;

export type ReviewInsert = Insert<
  ReviewRow,
  'booking_id' | 'author_user_id' | 'subject_user_id' | 'subject_type' | 'rating'
>;
export type ReviewUpdate = Partial<ReviewRow>;

// ---------------------------------------------------------------------------
// Aggregated `Database` shape - the type parameter for createClient<Database>
// ---------------------------------------------------------------------------

export interface Database {
  public: {
    Tables: {
      users: {
        Row: UserRow;
        Insert: UserInsert;
        Update: UserUpdate;
        Relationships: [];
      };
      companion_profiles: {
        Row: CompanionProfileRow;
        Insert: CompanionProfileInsert;
        Update: CompanionProfileUpdate;
        Relationships: [];
      };
      availability: {
        Row: AvailabilityRow;
        Insert: AvailabilityInsert;
        Update: AvailabilityUpdate;
        Relationships: [];
      };
      meal_requests: {
        Row: MealRequestRow;
        Insert: MealRequestInsert;
        Update: MealRequestUpdate;
        Relationships: [];
      };
      bookings: {
        Row: BookingRow;
        Insert: BookingInsert;
        Update: BookingUpdate;
        Relationships: [];
      };
      payments: {
        Row: PaymentRow;
        Insert: PaymentInsert;
        Update: PaymentUpdate;
        Relationships: [];
      };
      messages: {
        Row: MessageRow;
        Insert: MessageInsert;
        Update: MessageUpdate;
        Relationships: [];
      };
      reviews: {
        Row: ReviewRow;
        Insert: ReviewInsert;
        Update: ReviewUpdate;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      is_booking_participant: {
        Args: { p_booking_id: string };
        Returns: boolean;
      };
    };
    Enums: {
      meal_type: MealType;
      verification_status: VerificationStatus;
      request_status: RequestStatus;
      booking_status: BookingStatus;
      budget_tier: BudgetTier;
      payment_status: PaymentStatus;
      escrow_status: EscrowStatus;
      message_type: MessageType;
      review_subject_type: ReviewSubjectType;
      cancellation_party: CancellationParty;
    };
    CompositeTypes: Record<string, never>;
  };
}
